import { Router } from "express";
import { pool } from "../db";
import jwt from "jsonwebtoken";
import { env } from "../platform/env";
import { sendOtp, verifyOtp } from "../services/otpService";

const router = Router();
router.post("/referrer/otp/start", async (req, res) => { const phone = String(req.body?.phone ?? "").trim(); if (!phone) return res.status(400).json({ error: "phone_required" }); await sendOtp(phone); res.json({ ok: true }); });
router.post("/referrer/otp/verify", async (req, res) => { const phone = String(req.body?.phone ?? "").trim(); const code = String(req.body?.code ?? "").trim(); if (!await verifyOtp(phone, code)) return res.status(401).json({ error: "invalid_otp" }); let r = await pool.query(`SELECT * FROM bi_referrers WHERE phone=$1`, [phone]); if (!r.rows[0]) { await pool.query(`INSERT INTO bi_referrers (phone) VALUES ($1)`, [phone]); r = await pool.query(`SELECT * FROM bi_referrers WHERE phone=$1`, [phone]); } const ref = r.rows[0]; const token = jwt.sign({ kind: "referrer", id: ref.id }, env.JWT_SECRET || "dev-missing-jwt-secret", { expiresIn: "7d" }); res.json({ token, intake_complete: ref.intake_complete }); });
function requireReferrer(req: any, res: any, next: any) { const auth = String(req.headers.authorization ?? ""); if (!auth.startsWith("Bearer ")) return res.status(401).json({ error: "missing_token" }); try { const claims: any = jwt.verify(auth.slice(7), env.JWT_SECRET || "dev-missing-jwt-secret"); if (claims.kind !== "referrer") return res.status(403).json({ error: "wrong_session" }); req.referrerId = claims.id; next(); } catch { return res.status(401).json({ error: "invalid_token" }); } }
router.post("/referrer/intake", requireReferrer, async (req: any, res) => { const b = req.body ?? {}; const required = ["first_name","last_name","email","address_line1","city","province","postal_code","country"]; const missing = required.filter((k) => !b[k]); if (missing.length) return res.status(400).json({ error: "missing_fields", fields: missing }); await pool.query(`UPDATE bi_referrers SET first_name=$1, last_name=$2, email=$3, company_name=$4, address_line1=$5, address_line2=$6, city=$7, province=$8, postal_code=$9, country=$10, etransfer_email=$11, intake_complete=TRUE, updated_at=NOW() WHERE id=$12`, [b.first_name,b.last_name,b.email,b.company_name ?? null,b.address_line1,b.address_line2 ?? null,b.city,b.province,b.postal_code,b.country,b.etransfer_email ?? null,req.referrerId]); res.json({ ok: true }); });
router.get("/referrer/dashboard", requireReferrer, async (req: any, res) => { const r = await pool.query(`SELECT r.id, r.full_name, r.company_name, r.email, r.phone, r.status, r.created_at, a.id AS application_id, a.status AS application_status, a.annual_premium, a.business_name FROM bi_referrals r LEFT JOIN bi_applications a ON a.id = r.application_id WHERE r.referrer_id=$1 ORDER BY r.created_at DESC LIMIT 500`, [req.referrerId]); res.json({ referrals: r.rows }); });
router.post("/referrer/referrals", requireReferrer, async (req: any, res) => { const b = req.body ?? {}; const required = ["full_name","email","phone"]; const missing = required.filter((k) => !b[k]); if (missing.length) return res.status(400).json({ error: "missing_fields", fields: missing }); const r = await pool.query(`INSERT INTO bi_referrals (referrer_id, full_name, company_name, email, phone, status) VALUES ($1,$2,$3,$4,$5,'invited') RETURNING id`, [req.referrerId, b.full_name, b.company_name ?? null, b.email, b.phone]); await pool.query(`INSERT INTO bi_contacts (id, full_name, company_name, email, phone, tags, created_at, updated_at) VALUES (gen_random_uuid(), $1, $2, $3, $4, ARRAY['referral'], NOW(), NOW()) ON CONFLICT (email) DO UPDATE SET tags = (SELECT ARRAY(SELECT DISTINCT unnest(bi_contacts.tags || ARRAY['referral']))), updated_at = NOW()`, [b.full_name, b.company_name ?? null, b.email, b.phone]); res.status(201).json({ id: r.rows[0].id, status: "invited" }); });
export default router;
