ALTER TABLE bi_applications
ADD COLUMN IF NOT EXISTS directors JSONB,
ADD COLUMN IF NOT EXISTS has_bankruptcy BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS has_existing_pg BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS existing_pg_amount NUMERIC,
ADD COLUMN IF NOT EXISTS has_previous_claims BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS first_name TEXT,
ADD COLUMN IF NOT EXISTS last_name TEXT,
ADD COLUMN IF NOT EXISTS secured_type TEXT,
ADD COLUMN IF NOT EXISTS commission NUMERIC;
