-- BI_SERVER_SEED_AUG6_TEMPLATES_v12
-- Seeds the four BI campaign templates so they are picked from "Load template"
-- and cannot be lost. body_html stays NULL: the rendered HTML is produced by the
-- composer, not by SQL. Open each, add the image, then save under the same name.
-- Guarded by name so re-running never duplicates and never overwrites edits.

INSERT INTO bi_email_templates (name, subject, category, fields, is_active)
SELECT 'Aug 6th - Lenders', 'Close the deals your PG requirement is killing', 'email', '{"headline": "The guarantee stops being the deal-breaker", "heroUrl": "", "heroLink": "https://www.boreal.insure/?utm_source=email&utm_medium=marketing&utm_campaign=aug6-bi-lenders&utm_content=left", "body": "Strong borrowers walk away from good deals rather than put their home behind them. When that personal exposure is covered, they sign. You keep your security position and stop losing files at the last step.", "ctaLabel": "How PG cover works", "ctaUrl": "https://www.boreal.insure/?utm_source=email&utm_medium=marketing&utm_campaign=aug6-bi-lenders&utm_content=left", "headline2": "Nothing changes on your side", "body2": "Referral only. Your documents, your security, your process. We handle the applicant end to end and report back.", "rightImageUrl": "", "rightImageLink": "https://www.boreal.insure/?utm_source=email&utm_medium=marketing&utm_campaign=aug6-bi-lenders&utm_content=right", "cta2Label": "Get set up", "cta2Url": "https://www.boreal.insure/?utm_source=email&utm_medium=marketing&utm_campaign=aug6-bi-lenders&utm_content=right"}'::jsonb, TRUE
 WHERE NOT EXISTS (SELECT 1 FROM bi_email_templates WHERE name = 'Aug 6th - Lenders');

INSERT INTO bi_email_templates (name, subject, category, fields, is_active)
SELECT 'Aug 6th - Lawyers', '"Do I have to sign the personal guarantee?"', 'email', '{"headline": "The question you have one answer to", "heroUrl": "", "heroLink": "https://www.boreal.insure/?utm_source=email&utm_medium=marketing&utm_campaign=aug6-lawyers&utm_content=left", "body": "Your client asks it in every financing, every lease, every supply agreement. Today the answer is sign it or lose the deal. There is now a third option you can put on the table, and it costs you nothing to know about it.", "ctaLabel": "What PG cover is", "ctaUrl": "https://www.boreal.insure/?utm_source=email&utm_medium=marketing&utm_campaign=aug6-lawyers&utm_content=left", "headline2": "It is not just bank loans", "body2": "Landlords, suppliers, equipment lessors, franchisors, sureties and vendors taking back paper on a sale all demand personal guarantees. If you review commercial agreements, you see these clauses constantly.", "rightImageUrl": "", "rightImageLink": "https://www.boreal.insure/?utm_source=email&utm_medium=marketing&utm_campaign=aug6-lawyers&utm_content=right", "cta2Label": "See covered transaction types", "cta2Url": "https://www.boreal.insure/?utm_source=email&utm_medium=marketing&utm_campaign=aug6-lawyers&utm_content=right"}'::jsonb, TRUE
 WHERE NOT EXISTS (SELECT 1 FROM bi_email_templates WHERE name = 'Aug 6th - Lawyers');

INSERT INTO bi_email_templates (name, subject, category, fields, is_active)
SELECT 'Aug 6th - Referrers (bookkeepers, accountants)', 'The liability on your client''s balance sheet nobody''s pricing', 'email', '{"headline": "You see the guarantee before anyone else does", "heroUrl": "", "heroLink": "https://www.boreal.insure/?utm_source=email&utm_medium=marketing&utm_campaign=aug6-bi-referrers&utm_content=left", "body": "You are in the file. You know what they signed, what it secured, and what it would cost them personally if the business turned. Most owners have never once been told that exposure can be covered.", "ctaLabel": "Why it matters", "ctaUrl": "https://www.boreal.insure/?utm_source=email&utm_medium=marketing&utm_campaign=aug6-bi-referrers&utm_content=left", "headline2": "{{first_name}}, just make the introduction", "body2": "You do not need to explain the product or sell anything. Point them at us and we take it from there. You stay their accountant and they stop carrying an exposure they never priced.", "rightImageUrl": "", "rightImageLink": "https://www.boreal.insure/?utm_source=email&utm_medium=marketing&utm_campaign=aug6-bi-referrers&utm_content=right", "cta2Label": "Introduce a client", "cta2Url": "https://www.boreal.insure/?utm_source=email&utm_medium=marketing&utm_campaign=aug6-bi-referrers&utm_content=right"}'::jsonb, TRUE
 WHERE NOT EXISTS (SELECT 1 FROM bi_email_templates WHERE name = 'Aug 6th - Referrers (bookkeepers, accountants)');

INSERT INTO bi_email_templates (name, subject, category, fields, is_active)
SELECT 'Aug 6th - Untagged', 'Which of these are you?', 'email', '{"headline": "I lend, or I take personal guarantees", "heroUrl": "", "heroLink": "https://www.boreal.insure/?utm_source=email&utm_medium=marketing&utm_campaign=aug6-untagged&utm_content=left", "body": "Lenders, lessors, landlords, suppliers and sureties. If a personal guarantee is a condition of doing business with you, PG cover is how the deals you are losing get signed.", "ctaLabel": "I''m a lender", "ctaUrl": "https://www.boreal.insure/?utm_source=email&utm_medium=marketing&utm_campaign=aug6-untagged&utm_content=left", "headline2": "I advise business owners", "body2": "Lawyers, accountants and bookkeepers. Your clients sign personal guarantees constantly. Here is what to tell them when they ask whether they have to.", "rightImageUrl": "", "rightImageLink": "https://www.boreal.financial/referrer?utm_source=email&utm_medium=marketing&utm_campaign=aug6-untagged&utm_content=right", "cta2Label": "I''m an advisor", "cta2Url": "https://www.boreal.financial/referrer?utm_source=email&utm_medium=marketing&utm_campaign=aug6-untagged&utm_content=right"}'::jsonb, TRUE
 WHERE NOT EXISTS (SELECT 1 FROM bi_email_templates WHERE name = 'Aug 6th - Untagged');
