// BI_APOLLO_RUN_v55_PHASE3 — enroll contacts into Apollo sequences with ICP tagging.
import { pool } from "../../db";
import { logger } from "../../platform/logger";
import { addContactsToSequence, createApolloContact, matchPerson } from "./apolloClient";
import { upsertApolloContact } from "./apolloContactSync";
export const ICP_SEGMENTS = ["lender", "lawyer", "accountant", "cre_broker", "ma_broker"] as const;
export type IcpSegment = typeof ICP_SEGMENTS[number];
export async function tagContactIcp(contactId: string, icp: IcpSegment): Promise<void> { if (!ICP_SEGMENTS.includes(icp)) throw new Error(`invalid icp_segment: ${icp}`); await pool.query(`UPDATE bi_contacts SET icp_segment = $2 WHERE id = $1`, [contactId, icp]); }
async function ensureApolloId(contactId: string): Promise<string | null> { const r = await pool.query<any>(`SELECT id, full_name, email, phone_e164, apollo_contact_id FROM bi_contacts WHERE id = $1 LIMIT 1`, [contactId]); const row = r.rows[0]; if (!row) return null; if (row.apollo_contact_id) return row.apollo_contact_id; if (!row.email) return null; const [first,...rest] = row.full_name.split(/\s+/); const last = rest.join(" ") || undefined; try { const { person } = await matchPerson({ email: row.email, first_name: first, last_name: last }); if (person?.id) { await upsertApolloContact(person); return person.id; } } catch (err) { logger.warn({ err, contactId }, "matchPerson failed during enroll"); } try { const created = await createApolloContact({ first_name: first, last_name: last, email: row.email, phone: row.phone_e164 ?? undefined }); if (created?.id) { await upsertApolloContact(created); return created.id; } } catch (err) { logger.error({ err, contactId }, "createApolloContact failed during enroll"); } return null; }
export async function enrollContactsInSequence(opts: { sequenceId: string; contactIds: string[]; icpSegment?: IcpSegment; emailAccountId?: string }) { const skipped:any[]=[]; const apolloIds:string[]=[]; const idMap:Record<string,string>={}; for (const cid of opts.contactIds){ const apolloId = await ensureApolloId(cid); if(!apolloId){ skipped.push({contact_id:cid, reason:'no_apollo_id'}); continue;} apolloIds.push(apolloId); idMap[cid]=apolloId; if(opts.icpSegment){ try{ await tagContactIcp(cid, opts.icpSegment);} catch(err){ logger.warn({err,cid}, 'tagContactIcp failed'); } } } const bounceCheck = await pool.query<{id:string}>(`SELECT id FROM bi_contacts WHERE id = ANY($1::uuid[]) AND email_status = 'bounced'`, [Object.keys(idMap)]); for (const cid of bounceCheck.rows.map(r=>r.id)){ const aid=idMap[cid]; const i=apolloIds.indexOf(aid); if(i>=0) apolloIds.splice(i,1); skipped.push({contact_id:cid, reason:'email_bounced'});} const result = await addContactsToSequence(opts.sequenceId, apolloIds, opts.emailAccountId); if(apolloIds.length){ await pool.query(`UPDATE bi_contacts SET apollo_sequence_names = ARRAY(SELECT DISTINCT UNNEST(apollo_sequence_names || $2::text[])) WHERE apollo_contact_id = ANY($1::text[])`, [apolloIds, [opts.sequenceId]]);} return { sequenceId: opts.sequenceId, requested: opts.contactIds.length, enrolled: result.enrolled, skipped }; }
